// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJdserxp8xMzMyrvi8doUUkot9Xb6IcFk',
    appId: '1:553633504317:web:e6eebc2736a2261ab25e54',
    messagingSenderId: '553633504317',
    projectId: 'tastebookbase',
    authDomain: 'tastebookbase.firebaseapp.com',
    storageBucket: 'tastebookbase.firebasestorage.app',
    measurementId: 'G-45TYT90MY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ_TdcyDDite1CwyUl58k_pigKY6kx72w',
    appId: '1:553633504317:android:fc62c21a26f94e5eb25e54',
    messagingSenderId: '553633504317',
    projectId: 'tastebookbase',
    storageBucket: 'tastebookbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYMy0q3MVx4mcuVNnyhFXhm05FvFHyBSc',
    appId: '1:553633504317:ios:376c0969207ddb68b25e54',
    messagingSenderId: '553633504317',
    projectId: 'tastebookbase',
    storageBucket: 'tastebookbase.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYMy0q3MVx4mcuVNnyhFXhm05FvFHyBSc',
    appId: '1:553633504317:ios:376c0969207ddb68b25e54',
    messagingSenderId: '553633504317',
    projectId: 'tastebookbase',
    storageBucket: 'tastebookbase.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJdserxp8xMzMyrvi8doUUkot9Xb6IcFk',
    appId: '1:553633504317:web:58291f91fea5f09ab25e54',
    messagingSenderId: '553633504317',
    projectId: 'tastebookbase',
    authDomain: 'tastebookbase.firebaseapp.com',
    storageBucket: 'tastebookbase.firebasestorage.app',
    measurementId: 'G-NKBNGFMNV3',
  );

}